env: dev
app:
  name: productcatalogservice
  group: app
  replicaCount: 1
  container:
    name: server
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.5.0
    port: 3550
    config: []
    env:
    - name: PORT
      value: "3550"
    - name: DISABLE_PROFILER
      value: "1"
  service:
    name: grpc
    type: ClusterIP
    port: 3550
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    command: ["/bin/grpc_health_probe", "-addr=:3550"]
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    command: ["/bin/grpc_health_probe", "-addr=:3550"]