apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    {{ include "common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
        {{ include "common.labels" . | indent 4 }}
    spec:
      serviceAccountName: {{ if .Values.app.serviceAccountName | default "" }}
      terminationGracePeriodSeconds: {{ if .Values.app.terminationGracePeriodSeconds | default "" }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.container.image }}  
          ports:
            - containerPort: {{ .Values.app.container.port }}
          envFrom:
            {{- range .Values.app.container.config }}
            - configMapRef:
                name: {{ .name }}
            {{- end}}
          env:
            {{- range .Values.app.container.env}}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}
          readinessProbe:
            periodSeconds: {{ Values.app.readinessProbe.periodSeconds }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          livenessProbe:
            periodSeconds: {{ Values.app.livenessProbe.periodSeconds }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          resources:
            requests:
              cpu: {{ Values.app.resources.requests.cpu }}
              memory: {{ Values.app.resources.requests.memory }}
            limits:
              cpu: {{ Values.app.resources.limits.cpu }}
              memory: {{ Values.app.resources.limits.memory }}