name: Deploying GKE with Terraform

on:
  pull_request:
    branches:
      - main
    paths:
      - 'gcp/gke-deployment/*'
  release:
    types: [ created ]
    branches:
      - main
    paths:
      - 'gcp/gke-deployment/*'

jobs:
  TF_Dev:
    uses: ramirocastillo93/terraforming_gcp/.github/workflows/terraform.yml@feature/github-actions
    with:
      deployment_directory: gcp/gke-deployment
      var_file: dev.tfvars
      out_file: dev.tfplan
    secrets:
      google_credentials: ${{secrets.GOOGLE_CREDENTIALS}}

  TF_Prod:
    uses: ramirocastillo93/terraforming_gcp/.github/workflows/terraform.yml@feature/github-actions
    with:
      deployment_directory: gcp/gke-deployment
      var_file: prod.tfvars
      out_file: prod.tfplan
    secrets:
      google_credentials: ${{secrets.GOOGLE_CREDENTIALS}}