name: Deploying GKE with Terraform

on:
  # workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - gcp/gke-deployment/**
  release:
    types: [ created ]
    branches:
      - main
    paths:
      - gcp/gke-deployment/**

jobs:
  TF_Deploy:
    uses: ramirocastillo93/terraforming_gcp/.github/workflows/terraform.yml@feature/github-actions
    with:
      deployment_directory: gcp/gke-deployment
    secrets:
      google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}