name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  terraform:
    uses: ramirocastillo93/terraforming_gke/.github/workflows/terraform.yaml@main
    with:
      deployment_directory: gcp/gke-deployment
      var_file: dev.tfvars
      out_file: tfplan_dev
    secrets:
      google_credentials: ${{secrets.GOOGLE_CREDENTIALS}}