name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec_commenter:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: tfsec Commenter
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}